src/Sistema/IRMBundle/Entity/EntityImages.php
<?php

namespace Sistema\IRMBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Sistema\IRMBundle\Filter\userInterface;
use Rhumsaa\Uuid\Uuid;
/**
 * EntityImages
 *
 * @ORM\Table(name="entity_images")
 * @ORM\Entity(repositoryClass="Sistema\IRMBundle\Entity\EntityImagesRepository")
 * @ORM\MappedSuperclass
 * @ORM\HasLifecycleCallbacks
 */
class EntityImages extends MWSgedmo  {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="uuid", type="string", length=36, nullable=false)
     */
    private $uuid;

    /**
     * @var string
     *
     * @ORM\Column(name="typesIncluded", type="string", length=30, nullable=true)
     */
    private $typesincluded;

    /**
     * @var integer
     *
     * @ORM\Column(name="syncProcessTimeStamp", type="bigint", nullable=false)
     */
    private $syncprocesstimestamp;

    /**
     * @var integer
     *
     * @ORM\Column(name="isDeleted", type="integer", nullable=false)
     */
    private $isdeleted;

    /**
     * @var \Sistema\UserBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="Sistema\UserBundle\Entity\User", inversedBy="entityImages")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * })
     */
    private $user;

    /**
     * @Assert\File()
     */
    protected $fileCropped;

    /**
     * @var string
     *
     * @ORM\Column(name="file_path_Cropped", type="string", length=255, nullable=true)
     */
    protected $filePathCropped;

    /**
     * @var string
     */
    protected $tempCropped;

    /**
     * @var string
     */
    protected $uploadDir = 'uploads';

    /**
     * @Assert\File()
     */
    protected $fileSource;

    /**
     * @var string
     *
     * @ORM\Column(name="file_path_Source", type="string", length=255, nullable=true)
     */
    protected $filePathSource;

    /**
     * @var string
     */
    protected $tempSource;

    public function __construct() {
        $this->setIsdeleted(0);
    }

    public function __toString() {
        return (string) $this->getId();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set guid
     *
     * @param string $uuid
     * @return EntityImages
     */
    public function setUuid($uuid) {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Get guid
     *
     * @return string 
     */
    public function getUuid() {
        return $this->uuid;
    }

    /**
     * Set typesincluded
     *
     * @param string $typesincluded
     * @return EntityImages
     */
    public function setTypesincluded($typesincluded) {
        $this->typesincluded = $typesincluded;

        return $this;
    }

    /**
     * Get typesincluded
     *
     * @return string 
     */
    public function getTypesincluded() {
        return $this->typesincluded;
    }

    /**
     * Set syncprocesstimestamp
     *
     * @param integer $syncprocesstimestamp
     * @return EntityImages
     */
    public function setSyncprocesstimestamp($syncprocesstimestamp) {
        $this->syncprocesstimestamp = $syncprocesstimestamp;

        return $this;
    }

    /**
     * Get syncprocesstimestamp
     *
     * @return integer 
     */
    public function getSyncprocesstimestamp() {
        return $this->syncprocesstimestamp;
    }

    /**
     * Set isdeleted
     *
     * @param integer $isdeleted
     * @return EntityImages
     */
    public function setIsdeleted($isdeleted) {
        $this->isdeleted = $isdeleted;

        return $this;
    }

    /**
     * Get isdeleted
     *
     * @return integer 
     */
    public function getIsdeleted() {
        return $this->isdeleted;
    }

    /**
     * Set user
     *
     * @param \Sistema\UserBundle\Entity\user $user
     * @return EntityImages
     */
    public function setUser(\Sistema\UserBundle\Entity\User $user = null) {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Sistema\UserBundle\Entity\User 
     */
    public function getUser() {
        return $this->user;
    }

    /**
     * Set filePath
     *
     * @param  string $filePath
     * @return File
     */
    public function setFilePathCropped($filePathCropped) {
        $this->filePathCropped = $filePathCropped;

        return $this;
    }

    /**
     * Get FilePathCropped
     *
     * @return string
     */
    public function getFilePathCropped() {
        return $this->filePathCropped;
    }

    /**
     * Set filePath
     *
     * @param  string $filePathCropped
     * @return File
     */
    public function setFilePathSource($filePathSource) {
        $this->filePathSource = $filePathSource;

        return $this;
    }

    /**
     * Get FilePathSource
     *
     * @return string
     */
    public function getFilePathSource() {
        return $this->filePathSource;
    }

    /**
     * Set file
     *
     * @param UploadedFile $file
     */
    public function setFileCropped($file = null) {
        $this->fileCropped = $file;
        // check if we have an old image path
        if (is_file($this->getAbsolutePath($this->filePathCropped))) {
            // store the old name to delete after the update
            $this->tempCropped = $this->getAbsolutePath($this->filePathCropped);
        }
    }

    /**
     * Get file
     *
     * @return UploadedFile
     */
    public function getFileCropped() {
        return $this->fileCropped;
    }

    /**
     * Set file
     *
     * @param UploadedFile $file
     */
    public function setFileSource($file = null) {
        $this->fileSource = $file;
        // check if we have an old image path
        if (is_file($this->getAbsolutePath($this->filePathSource))) {
            // store the old name to delete after the update
            $this->tempSource = $this->getAbsolutePath($this->filePathSource);
        }
    }

    /**
     * Get file
     *
     * @return UploadedFile
     */
    public function getFileSource() {
        return $this->fileSource;
    }

    public function getAbsolutePath($filePath) {
        return is_null($filePath) ? null : $this->getUploadRootDir() . '/' . $filePath
        ;
    }

    public function getWebPathCropped() {
        return is_null($this->filePathCropped) ? $this->getUploadDir() . '/../bundles/sistemairm/img/img_default.png' : $this->getUploadDir() . '/' . $this->getUser()->getUuid() . '/' . $this->filePathCropped
        ;
    }

    public function getWebPathSource() {
        return is_null($this->filePathSource) ? $this->getUploadDir() . '/../bundles/sistemairm/img/img_default.png' : $this->getUploadDir() . '/' . $this->getUser()->getUuid() . '/' . $this->filePathSource
        ;
    }

    protected function getUploadRootDir() {
        if (!$this->getUploadDir()) {
            $uploadDir = 'uploads';
        } else {
            $uploadDir = $this->getUploadDir();
        }

        $path = __DIR__ . '/../../../../web/' . $uploadDir;

        if (!file_exists($path)) {
            mkdir($path, 0755);
        }

        return $path;
    }

    public function setUploadDir($uploadDir) {
        $this->uploadDir = $uploadDir;
    }

    public function getUploadDir() {
        return $this->uploadDir;
    }

    /**
     * @ORM\PreFlush()
     */
    public function preUpload() {
        if (!is_null($this->getFileCropped())) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->filePathCropped = $filename . "_cropped.png"; //. '.' // $this->getFileCropped()->guessExtension();
        }
        if (!is_null($this->getFileSource())) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->filePathSource = $filename . "_source.png"; //. '.' //$this->getFileSource()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (!is_null($this->getFileCropped())) {
            // if there is an error when moving the file, an exception will
            // be automatically thrown by move(). This will properly prevent
            // the entity from being persisted to the database on error
            if ($this->getFileCropped()instanceof UploadedFile) {
                $this->getFileCropped()->move($this->getUploadRootDir(), $this->filePathCropped);
            } else {
                file_put_contents($this->getUploadRootDir() . '/' . $this->filePathCropped, $this->getFileCropped());
            }
            // check if we have an old image
            if (isset($this->tempCropped)) {
                if (file_exists($this->tempCropped)) {
                    // delete the old image
                    unlink($this->tempCropped);
                }
                // clear the temp image path
                $this->tempCropped = null;
            }
            $this->fileCropped = null;
        }
        if (is_null($this->getFileSource())) {
            return null;
        } else {

            // if there is an error when moving the file, an exception will
            // be automatically thrown by move(). This will properly prevent
            // the entity from being persisted to the database on error
            if ($this->getFileSource()instanceof UploadedFile) {
                $this->getFileSource()->move($this->getUploadRootDir(), $this->filePathSource);
            } else {
                file_put_contents($this->getUploadRootDir() . '/' . $this->filePathSource, $this->getFileSource());
            }

src/Sistema/IRMBundle/Form/ProductsType.php
<?php

namespace Sistema\IRMBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Sistema\IRMBundle\Form\OrderItemsType;
use Sistema\IRMBundle\Form\PricesType;
use Sistema\IRMBundle\Form\PriceModifiersType;

/**
 * ProductsType form.
 * @author Nombre Apellido <name@gmail.com>
 */
class ProductsType extends AbstractType {

    private $allowOrdening = false;
    private $visible = false;
    private $deleted = false;

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        //allowOrdening
        if ($builder->getData()->getAllowordering() == 1) {
            $this->allowOrdening = true;
        } else {
            $this->allowOrdening = false;
        }//visible
        if ($builder->getData()->getVisible() == 1) {
            $this->visible = true;
        } else {
            $this->visible = false;
        }
        //deleted
        if ($builder->getData()->getIsDeleted() == 1) {
            $this->deleted = true;
        } else {
            $this->deleted = false;
        }

        $builder
                //->add('guid')
                ->add('foreignCode')
                ->add('name')
                ->add('description')
                ->add('code')
                //->add('visible')
                ->add('status', 'choice', array(
                    'required' => true,
                    'choices' => array(
                        0 => 'Available',
                        1 => 'Unavailable',
                    ),
                ))
                //->add('allowordering')
                /* ->add('menu', 'select2', array(
                  'class' => 'Sistema\IRMBundle\Entity\Menus',
                  'url' => 'Products_autocomplete_menu',
                  'configs' => array(
                  'multiple' => false, //required true or false
                  'width' => 'off',
                  ),
                  'attr' => array(
                  'class' => "col-lg-12 col-md-12 col-sm-12 col-xs-12",
                  )
                  )) */
                /* ->add('image', 'select2', array(
                  'class' => 'Sistema\IRMBundle\Entity\EntityImages',
                  'url' => 'Products_autocomplete_image',
                  'configs' => array(
                  'multiple' => false, //required true or false
                  'width' => 'off',
                  ),
                  'attr' => array(
                  'class' => "col-lg-12 col-md-12 col-sm-12 col-xs-12",
                  )
                  )) */
                ->add('folder', 'select2', array(
                    'class' => 'Sistema\IRMBundle\Entity\Folders',
                    'url' => 'Products_autocomplete_folder',
                    'configs' => array(
                        'multiple' => false, //required true or false
                        'width' => 'off',
                    ),
                    'attr' => array(
                        'class' => "col-lg-12 col-md-12 col-sm-12 col-xs-12",
                    ),
                    'required' => true,
                ))
                /* ->add('orderItems', 'collection', array(
                  'label_attr' => array(
                  'class' => 'col-lg-2 col-md-2 col-sm-2',
                  ),
                  'attr' => array(
                  'class' => 'col-lg-4 col-md-4 col-sm-4',
                  ),
                  'label' => false,
                  'type' => new OrderItemsType(),
                  'allow_add' => true,
                  'allow_delete' => true,
                  'required' => true,
                  'prototype' => true,
                  'prototype_name' => '__name__',
                  'by_reference' => false,
                  )) */
                ->add('prices', 'collection', array(
                    'label_attr' => array(
                        'class' => 'col-lg-2 col-md-2 col-sm-2',
                    ),
                    'attr' => array(
                        'class' => 'col-lg-4 col-md-4 col-sm-4',
                    ),
                    'label' => false,
                    'type' => new PricesType(),
                    'allow_add' => true,
                    'allow_delete' => true,
                    'required' => true,
                    'by_reference' => false,
                ))
                ->add('modifierPrices', 'collection', array(
                    'label_attr' => array(
                        'class' => 'col-lg-2 col-md-2 col-sm-2',
                    ),
                    'attr' => array(
                        'class' => 'col-lg-4 col-md-4 col-sm-4',
                    ),
                    'label' => false,
                    'type' => new PriceModifiersType(),
                    'allow_add' => true,
                    'allow_delete' => true,
                    'required' => true,
                    'by_reference' => false,
                ))
                ->add('allowOrdening', 'checkbox', array(
                    'mapped' => false,
                    'label' => 'AllowOrdening',
                    'required' => false,
                    'data' => $this->allowOrdening
                ))
                ->add('visible', 'checkbox', array(
                    'mapped' => false,
                    'label' => 'Visible',
                    'required' => false,
                    'data' => $this->visible
                ))
                ->add('deleted', 'checkbox', array(
                    'mapped' => false,
                    'label' => 'Is Deleted',
                    'required' => false,
                    'data' => $this->deleted
                ))
                ->add('tags')
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'Sistema\IRMBundle\Entity\Products'
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'sistema_irmbundle_products';
    }

}

src/Sistema/IRMBundle/Resources/views/Products/edit.html.twig
{% extends 'MWSimpleAdminCrudBundle::layout.html.twig' %}

{% block title %}
    {{ parent() }} - {{ 'views.edit.edit'|trans({'%entity%': config.entityName}, 'MWSimpleAdminCrudBundle') }}
{% endblock %}

{% block page %}
    {% form_theme edit_form 'MWSimpleAdminCrudBundle:widget:fields.html.twig' %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary center-block">
                <div class="panel-heading">
                    <i class="glyphicon glyphicon-pencil"></i> {{ 'views.edit.edit'|trans({'%entity%': config.entityName}, 'MWSimpleAdminCrudBundle') }}
                </div>
                <div class="panel-body">
                    {% block form %}
                        {% form_theme edit_form 'SistemaIRMBundle:Form:form-product-theme.html.twig' %}
					    {{ form(edit_form) }}
					    {% include 'SistemaIRMBundle:Form:macro-viewEntityImagesNew.html.twig' with {'formEntityImage' : formEntityImage}%}     
					    <script src="{{ asset('bundles/mwsimpleadmincrud/js/addForm.js') }}"></script>
					    <script type='text/javascript' src='{{ asset('bundles/sistemairm/js/handlebars-v1.3.0.js') }}'></script> 
					    <script type='text/javascript' src='{{ asset('bundles/sistemairm/js/metodosHandlebar.js') }}'></script>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3">
            <a class="form-control btn btn-info" href="{{ path(config.index) }}">
                {{ 'views.recordactions.backtothelist'|trans({}, 'MWSimpleAdminCrudBundle') }}
            </a>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/mwsimpleadmincrud/js/widget.js') }}"></script>
{% endblock %}

src/Sistema/IRMBundle/Resources/views/Products/new.html.twig
{% extends 'MWSimpleAdminCrudBundle:Default:new.html.twig' %}

{% block form %}  
 
    {% form_theme form 'SistemaIRMBundle:Form:form-product-theme.html.twig' %}
    {{ form(form) }}
    {% include 'SistemaIRMBundle:Form:macro-viewEntityImagesNew.html.twig' with {'formEntityImage' : formEntityImage}%}     
    <script src="{{ asset('bundles/mwsimpleadmincrud/js/addForm.js') }}"></script>
    <script type='text/javascript' src='{{ asset('bundles/sistemairm/js/handlebars-v1.3.0.js') }}'></script> 
    <script type='text/javascript' src='{{ asset('bundles/sistemairm/js/metodosHandlebar.js') }}'></script>
    
{% endblock %}

src/Sistema/IRMBundle/Resources/views/Products/show.html.twig
{% extends 'MWSimpleAdminCrudBundle:Default:show.html.twig' %}

{% block page %}
    {% import "SistemaIRMBundle:Form:macro-price.html.twig" as macrosPrice %}
    {% import "SistemaIRMBundle:Form:macro-price.html.twig" as macrosModifierPrice %}
    <style type="text/css">
        .not-active {
            pointer-events: none;
            cursor: default;
        }
    </style>
    <div class="panel panel-primary center-block">
        <div class="panel-heading">
            <i class="glyphicon glyphicon-ok"></i> {{ 'views.show.show'|trans({'%entity%': config.entityName}, 'MWSimpleAdminCrudBundle') }}
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4"> 
                    <div class="form-group">
                        <label class="control-label">uuid</label>
                        <div class="form-control">
                            <span class="input-xlarge uneditable-input">
                                {{entity.uuid }}
                            </span>
                        </div>
                    </div>
                </div> 
                <div class="col-lg-4 col-md-4 col-sm-4"> 
                    <label class="control-label">foreignCode</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.foreignCode }}
                        </span>
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4"> 
                    <label class="control-label">name</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.name }}
                        </span>
                    </div>

                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3"> 
                    <label class="control-label">status</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {% if entity.status == 0 %}
                                Available                
                            {% else %}  
                                Unavailable
                            {% endif %}
                        </span>
                    </div>

                </div>
                <div class="col-lg-3 col-md-3 col-sm-3"> 
                    <label class="control-label">code</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.code }}
                        </span>
                    </div>

                </div>
                <div class="col-lg-3 col-md-3 col-sm-3"> 
                    <label class="control-label">Visible?</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.visible ? isActive(true, 'Producto Visible', 'Producto Oculto') : isActive(false, 'Producto Visible', 'Producto Oculto') }}
                        </span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3"> 
                    <label class="control-label">Is Deleted?</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.isdeleted ? isActive(true, 'Producto Activo', 'Producto Borrado') : isActive(false, 'Producto Activo', 'Producto Borrado') }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label class="control-label">description</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.description }}
                        </span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3">
                    <label class="control-label">allowordering</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.allowordering ? isActive(true, 'Product Orderning', 'Product not Orderning') : isActive(false, 'Product Orderning', 'Product not Borrado') }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4"> 
                    <label class="control-label">folder</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.folder }}
                        </span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4"> 
                    <label class="control-label">image</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.image }}
                        </span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">   
                    <label class="control-label">menu</label>
                    <div class="form-control">
                        <span class="input-xlarge uneditable-input">
                            {{ entity.menu }}
                        </span>
                    </div>
                </div>
            </div>

            <div role="tabpanel">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#price" aria-controls="price" role="tab" data-toggle="tab">Price</a></li>
                    <li role="presentation"><a href="#modifierPrice" aria-controls="modifierPrice" role="tab" data-toggle="tab">Modifier Price</a></li>
                    <li role="presentation"><a href="#imagen" aria-controls="imagen" role="tab" data-toggle="tab">Imagen</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="price">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row" style="text-align:center;">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <label>Nombre</label>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <label>Amount</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <ul class="list-group">
                                            {% for price in entity.prices %}
                                                <li class="list-group-item">
                                                    {{ macrosPrice.prototipoPriceShow(price) }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="modifierPrice">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row" style="text-align:center;">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <label>Nombre</label>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <label>Amount</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <ul class="list-group">

                                            {% for price in entity.modifierPrices %}
                                                <li class="list-group-item">
                                                    {{ macrosPrice.prototipoPriceShow(price) }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="imagen">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-xs-6 ">
                                        <label>Cropped</label> </br> 
                                        {% if entity.image.filePathCropped is defined %}
                                            <img  src="{{ asset(entity.image.webPathCropped) }}" class="img-rounded" style=" width: 70%;"> 
                                        {% else %}
                                            <img  src="{{ asset('bundles/sistemairm/img/img_default.png') }}" class="img-rounded" style=" width: 70%;"> 
                                        {% endif%}
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-xs-6 ">
                                        <label>Source</label></br>
                                        {% if entity.image.filePathSource is defined %}
                                            <img  src="{{ asset(entity.image.webPathSource) }}" class="img-rounded" style=" width: 70%;">
                                        {% else %}
                                            <img  src="{{ asset('bundles/sistemairm/img/img_default.png') }}" class="img-rounded" style=" width: 70%;">
                                        {% endif%}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>      
        </div>
    </div>
    <div class="col-lg-9">
        <div class="float-left col-lg-3">
            <a class="btn btn-info col-lg-11" href="{{ path(config.index) }}">
                {{ 'views.recordactions.backtothelist'|trans({}, 'MWSimpleAdminCrudBundle') }}
            </a>
        </div>
        <div class="float-left col-lg-3">
            <a class="btn btn-primary col-lg-11" href="{{ path(config.edit, { 'id': entity.id }) }}">
                {{ 'views.recordactions.edit'|trans({'%entity%': config.entityName}, 'MWSimpleAdminCrudBundle') }}
            </a>
        </div>
        <div class="float-left col-lg-3">{{ form(delete_form) }}</div>
    </div>
{% endblock %}